#!/usr/bin/env bash
python qg.py \
  --model_name_or_path "flan-t5-QG" \
  --final_model_dir "ckpts/flan-t5-querygen" \
  --special_token 32000 \
  --dataset_path "/home/ricky/dodofk/dataset/slue_sqa5/" \
  --code_path "/home/ricky/dodofk/dataset/slue_sqa_code_c512" \
  --split train \
  --max_length 512 \
  --discrete_code_num 512 \
  --project "Audio-QG" \
  --description "Query generation on SLUE-SQA5 with discrete units from flan-t5-base" \
  --output_dir "ckpts/flan-t5-QG" \
  --per_device_train_batch_size 8 \
  --per_device_eval_batch_size 4 \
  --gradient_accumulation_steps 8 \
  --learning_rate 1e-4 \
  --evaluation_strategy steps \
  --eval_steps 2500 \
  --max_steps 100000 \
  --logging_steps 100 \
  --save_strategy steps \
  --save_steps 2000 \
  --save_total_limit 3 \
  --bf16 \
  --report_to "wandb"
